### ISSUE TITLE
ImportError: No module named typing

### ISSUE THREAD

**Issue by sldx12** [Cebtenzzre/tumblr-utils#1]
When trying to run the latest version I get the following error: 

```
Traceback (most recent call last):
  File "tumblr_backup.py", line 23, in <module>
    from typing import TYPE_CHECKING
ImportError: No module named typing
```

I have tried importing the module but to no success.

**Comment by Cebtenzzre** [comment]
It is recommended to use Python 3 with this fork. I unintentionally wrote the code to assume you have the `typing` module installed on Python 2, but I should be able to make it an optional dependency.

**Comment by sldx12** [comment]
My bad, since I had to use Python2 with the original fork I got used to it.

**Comment by Cebtenzzre** [comment]
Well, this issue was supposed to be closed by (and correctly linked to) those two commits, but you closed it early and GitHub got confused. Oh well.

**Comment by Cebtenzzre** [comment]
@sldx12 By the way, I recommended this fork to you because it has the `--cookiefile` option, which you can use if you go to Tumblr and dump the cookies to a file with an extension like [cookies.txt (Chrome)](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en) or [cookies.txt (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/). On the svc branch cookies are used for all API requests. I don't know whether the standard API even looks at cookies so it's just a shot in the dark.
